print('Укажите имя кошки 1:')
catName1 = input()
print('Укажите имя кошки 2:')
catName2 = input()
print('Укажите имя кошки 3:')
catName3 = input()
print('Укажите имя кошки 4:')
catName4 = input()
print('Укажите имя кошки 5:')
catName5 = input()
print('Укажите имя кошки 6:')
catName6 = input()
print('Имена котиков и кошек:')
print(catName1, catName2, catName3, catName4, catName5, catName6)
